# Generated by Django 3.2.13 on 2022-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFF', max_length=9, verbose_name='Цвет'),
        ),
    ]
