# Generated by Django 3.2.13 on 2022-05-14 08:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0003_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
