# Generated by Django 3.2.13 on 2022-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220504_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                null=True, upload_to="uploads/", verbose_name="Аватарка"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile",
            field=models.PositiveIntegerField(null=True, verbose_name="Номер телефона"),
        ),
    ]
