# Generated by Django 3.2.13 on 2022-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220505_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
    ]
