# Generated by Django 3.2.12 on 2022-05-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_username'),
        ('users', '0007_auto_20220511_1912'),
    ]

    operations = [
    ]
