# Generated by Django 3.2.13 on 2022-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/user.jpg', null=True, upload_to='uploads/', verbose_name='Аватарка'),
        ),
    ]
