# Generated by Django 3.2.13 on 2022-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upload",
            field=models.ImageField(
                null=True, upload_to="uploads/", verbose_name="Главное изображение"
            ),
        ),
    ]
