# Generated by Django 3.2.13 on 2022-05-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_auto_20220517_1516"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
