# Generated by Django 3.2.13 on 2022-05-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_alter_comment_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="PostComment",
        ),
        migrations.DeleteModel(
            name="ReplyComment",
        ),
        migrations.DeleteModel(
            name="UserComment",
        ),
    ]
