# Generated by Django 3.2.13 on 2022-05-24 09:07

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("description", "0008_tag_taggedwhatever"),
        ("posts", "0015_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="description.TaggedWhatever",
                to="description.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
