# Generated by Django 3.2.13 on 2022-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220525_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='uploads/', verbose_name='Изображение', width_field='width'),
        ),
    ]
