# Generated by Django 3.2.13 on 2022-05-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0009_alter_tag_options'),
        ('posts', '0019_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='description.category', verbose_name='Категория'),
        ),
    ]
